spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:43306/web_board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
